server:
  port: 9099


myconfig:
  command-queue-name: CommandQueue
  push-to-nginx-stream-prefix: rtmp://192.168.11.74:1935/hls/stream_

spring:
  activemq:
    broker-url: tcp://192.168.11.73:61616
    user: test
    password: 123456
    send-timeout: 3000

  datasource:
    username: starnet
    password: STARnet002396
    url: jdbc:mysql://127.0.0.1:3306/ipc_monitor?useUnicode=true&charaterEncoding=utf8mb4&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true&allowMultiQueries=true&cachePrepStmts=true&prepStmtCacheSqlLimit=2048&prepStmtCacheSize=256&useServerPrepStmts=true
  redis:
    host: localhost
    port: 6379
    password: STARnet002396
  jms:
    template:
      # mq发送消息超时时间 30s
      receive-timeout: 30000

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

